site_name: FERMO Documentation
site_description: Documentation for FERMO metabolomics software
site_author: Mitja M. Zdouc
copyright: '&copy; 2022 to present <a href="https://github.com/mmzdouc" target="_blank" rel="noopener">Mitja M. Zdouc</a> and individual contributors'

docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
  favicon: assets/images/favicon-fermo.svg
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home:
      - About: index.md
      - Why FERMO?: home/why_fermo.md
      - Input/Output: home/input_output.md
      - Fermo GUI:
          - Overview: home/gui.overview.md
          - Start Analysis: home/gui.start.md
          - Load Session: home/gui.load.md
          - Dashboard: home/gui.dashboard.md
          - Installation: home/gui.installation.md
      - fermo_core:
          - Overview: home/core.overview.md
          - Installation: home/core.installation.md
  - Modules:
      - Modules Overview: modules/overview.md
      - Filtering:
          - MS/MS Filtering: modules/filter.msms.md
          - Feature Filtering: modules/filter.feature.md
      - Networking:
          - Spectral Similarity: modules/networking.md
      - Annotation:
          - Adduct Ions: modules/annotation.adduct.md
          - Fragments: modules/annotation.fragment.md
          - Neutral Loss: modules/annotation.loss.md
          - User Library: modules/annotation.userlib.md
          - MS2Query: modules/annotation.ms2query.md
          - antiSMASH KCB: modules/annotation.as_kcb.md
      - Group Metadata:
          - Blank Assignment: modules/metadata.blank.md
          - Group Assignment: modules/metadata.group_fold.md
      - Phenotype:
          - Qualitative: modules/phenotype.qualitative.md
          - Quantitative-Percentage: modules/phenotype.quant-percent.md
          - Qualitative-Concentration: modules/phenotype.quant-concentr.md
      - Scores:
          - Feature Scores: modules/scores.features.md
          - Sample Scores: modules/scores.samples.md

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fermo-metabolomics/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html